/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.5/userguide/building_swift_projects.html in the Gradle documentation.
 */
@file:Suppress("UnstableApiUsage")

rootProject.name = "project-environment-plugin"

pluginManagement {
    repositories {
        mavenLocal() // Only for testing purposes
        mavenCentral()
        google()
        maven {
            setUrl("https://plugins.gradle.org/m2/")
        }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenLocal() // Only for testing purposes
        mavenCentral()
        google()
        maven {
            setUrl("https://plugins.gradle.org/m2/")
        }
    }
}

include("plugin")
