/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uo.project.environment;

import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * A simple unit test for the 'uo.project.environment.greeting' plugin.
 */
class ProjectEnvironmentPluginPluginTest {
    @Test
    void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("uo.project.environment.greeting");

        // Verify the result
        assertNotNull(project.getTasks().findByName("greeting"));
    }
}
